name = "PlantGeom"
uuid = "5edaa67e-25db-4eb9-bf81-05d793b2238d"
authors = ["remi.vezy <VEZY@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
